### ISSUE TITLE
Documentation of REST API

### ISSUE THREAD

**Issue by rogerioacp** [admin-ch/CovidCode-UI#1]
Hi, 

First I would like to thank you for making all of these projects open-source. They are really useful.

Secondly I would like to know if there is any plan to release some documentation on the interactions between the multiple components of the frontend, CovidCode-UI, CovidCode-Service and Keycloack.  More concretely, it would be useful to know which requests are made, the body of the requests and the information that must be stored on the tokens generated by the keycloack.

I was able to put everything working and infer these properties after some considerable effort. But it would really be helpful for  anyone else using these projects and  to keep up to date with any modification.

Thank you for your help.

**Comment by Quietghost** [comment]
Hi Rogério,

we are currently working on more documentation in that regard and it should be ready this week.

Best
Seb

**Comment by Brocy** [comment]
Hi hello from Cabo Verde

First of all thank you for the amazing job

Me and my team we are working to adapt this solution for our country Cabo Verde with the total support of our Government and I will like to endorse @rogerioacp request 

Is been a challenge to put everything working and infer these properties.

Please it will be really helpful

**Comment by Quietghost** [comment]
Hi Brocy and Rogério,

thank you for your comments ... not sure if you saw it already but we started to document the UI and the backend service in the Wiki of the repo so you can check there. I will also publish today or tomorrow our Keycloak configuration so that it is easier to get everything running.

And if you have more specific questions let us know.

**Comment by Brocy** [comment]
Thanks @Quietghost we are struggling with the keycloak configuration 

WARN  [ha-authcodegeneration,c4db72d401e83070] c.a.b.c.a.c.s.v.AudienceJwtValidator - The token is is not valid for audience 'ha-authcodegeneration'. 

WARN  [ha-authcodegeneration,c4db72d401e83070] c.a.b.c.a.c.s.v.ContextIssuerJwtValidator - Context claim 'ctx' is missing from the JWT.

We have some other questions, its is possible to have one session 15min to discuss some of them. 

https://www.linkedin.com/in/brocycenteio/

**Comment by Brocy** [comment]
I was able to put everything working, by creating a Custom Mappers for audience and ctx:USER

**Comment by Quietghost** [comment]
Hi all,

we finished the docmnentation of the Keycloak part - finally - and also provide now an example realm export from our dev environment (see the Wiki section). So you can just import it and everything should work. This export is alos used in the new docker-compose file.

I will close this issue then and let me know if you need more info ...
