### ISSUE TITLE
Setup environment funtioniert nicht - fatal: konnte nicht auf 'https://stash.eap.bit.admin.ch/scm/bag_covidcode/ha-ui.git/' zugreifen: Couldn't resolve host 'stash.eap.bit.admin.ch'

### ISSUE THREAD

**Issue by zdavatz** [admin-ch/CovidCode-UI#2]
Ich versuche:

`git clone https://stash.eap.bit.admin.ch/scm/bag_covidcode/ha-ui.git`

und erhalte:

`fatal: konnte nicht auf 'https://stash.eap.bit.admin.ch/scm/bag_covidcode/ha-ui.git/' zugreifen: Couldn't resolve host 'stash.eap.bit.admin.ch'`

**Comment by gillerr** [comment]
Das ist unseres private git repo. 
Wir sind in den Prozess alles auf GitHub zu migrieren. Readme ist nicht aktuell, repo link muss mit git  `https://github.com/admin-ch/CovidCode-UI.git` angepasst werden.

**Comment by zdavatz** [comment]
Ok, Danke für die Info.

**Comment by gillerr** [comment]
@zdavatz ich habe jetzt neu deployed, leider mit eine `push --force`, damit die ganze History dabei ist. Also bitte repo neu clonen.

**Comment by zdavatz** [comment]
ok, Danke.
